[profile.default]
solc_version = "0.8.24"
evm_version = "paris" # prevent use of PUSH0 opcode until it is widely supported
optimizer = true
via_ir = true
extra_output = ["metadata", "storageLayout", "evm.deployedBytecode.immutableReferences"]

libs = [
    "lib",
]

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
    "permit2/=lib/permit2/src/",
    "wormhole-sdk/=lib/wormhole-solidity-sdk/src/",
    "liquidity-layer/=lib/example-liquidity-layer/evm/src/",
    "local-modules/=lib/example-liquidity-layer/evm/forge/modules/",
    "swap-layer/=src",
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config
