disallowed-methods = [
    { path = "std::option::Option::and", reason = "prefer `and_then` for lazy evaluation" },
    { path = "std::option::Option::map_or", reason = "prefer `map_or_else` for lazy evaluation" },
    { path = "std::option::Option::ok_or", reason = "prefer `ok_or_else` for lazy evaluation" },
    { path = "std::option::Option::and", reason = "prefer `and_then` for lazy evaluation" },
]
