name: solana
on:
  push:
    branches:
      - main
  pull_request:

env:
  ANCHOR_VERSION: 0.30.1
  NODE_VERSION: 20.11.0
  RUSTC_VERSION: 1.75.0
  SOLANA_VERSION: 1.18.15
jobs:
  make-cargo-test-all:
    name: make cargo-test-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
          components: clippy, rustfmt
      - name: make cargo-test-all
        run: make cargo-test-all
        working-directory: ./solana

  make-lint:
    name: make lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
          components: clippy, rustfmt
      - name: make lint
        run: make lint
        working-directory: ./solana

  make-anchor-test:
    name: make anchor-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Solana CLI tools
        run: sh -c "$(curl -sSfL https://release.anza.xyz/v${{ env.SOLANA_VERSION }}/install)"
        shell: bash
      - name: Update PATH
        run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
        shell: bash
      - name: Install Anchor
        run: npm i -g @coral-xyz/anchor-cli@${{ env.ANCHOR_VERSION }}
        shell: bash
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
      - name: make anchor-test
        run: make anchor-test
        working-directory: ./solana

  make-check-build:
    name: make check-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - uses: metadaoproject/setup-anchor@v2
        with:
          node-version: "20.11.0"
          solana-cli-version: "1.18.15"
          anchor-version: "0.30.1"
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
      - name: make check-build
        run: make check-build
        working-directory: ./solana
